In [3]:
import numpy as np


In [57]:
#1.Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a_1 = np.arange(1, 11, 1)
print(a)
print(a_1)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [58]:
#2.Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
a_2 = np.zeros((3, 3))
print(a_2)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [59]:
#3.Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
a_3 = np.random.randint(1, 11, (5, 5))
print(a_3)

[[3 6 1 3 5]
 [9 2 9 7 5]
 [6 4 7 7 4]
 [5 1 1 7 6]
 [5 2 3 2 8]]


In [60]:
#4.Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
a_4 = np.random.rand(4, 4)
print(a_4)

[[0.92947093 0.85871181 0.17645221 0.52246518]
 [0.46058704 0.3607961  0.28920603 0.33963632]
 [0.54724765 0.48652631 0.00531986 0.2971255 ]
 [0.60126195 0.07965512 0.73521066 0.59844596]]


In [21]:
#5.Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.
b = np.random.randint(1, 11, (5, ))
c = np.random.randint(1, 11, (5, ))
print(b + c)
print(b - c)
print(b * c)

[ 6  8  6 18 10]
[-4  4 -4  0 -8]
[ 5 12  5 81  9]


In [56]:
#6.Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.
b_1 = np.random.random(7)
c_1 = np.random.random(7)
d = np.dot(b_1, c_1)
print(b_1)
print(c_1)
print(d)


[0.53636953 0.369576   0.33441472 0.90172747 0.78205814 0.72798565
 0.73406964]
[0.06813248 0.68415773 0.31080787 0.41463881 0.19663262 0.27654722
 0.59708787]
1.56062701975234


In [35]:
#7.Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
b_2 = np.random.randint(1, 11, (2, 2))
c_2 = np.random.randint(1, 11, (2, 3))
res_7= np.dot(b_2, c_2)
print(res_7)

[[103  30  98]
 [ 80  24  79]]


In [29]:
#8.Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
a_8 = np.random.randint(1, 11, (3, 3))
a_inv = np.linalg.inv(a_8)
print(a_inv)


[[-0.21917808 -0.13242009  0.36986301]
 [ 0.23287671  0.03652968 -0.20547945]
 [ 0.06849315  0.18721461 -0.17808219]]


In [30]:
#9.Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
a_9 = np.random.rand(4, 4)
a_tr = np.transpose(a_9)
print(a_9)
print(a_tr)

[[0.05567342 0.06760543 0.37414678 0.82976407]
 [0.52122397 0.60837923 0.00970035 0.29976468]
 [0.08050806 0.21967129 0.15208578 0.06658484]
 [0.45647693 0.42969037 0.17785551 0.33129544]]
[[0.05567342 0.52122397 0.08050806 0.45647693]
 [0.06760543 0.60837923 0.21967129 0.42969037]
 [0.37414678 0.00970035 0.15208578 0.17785551]
 [0.82976407 0.29976468 0.06658484 0.33129544]]


In [32]:
#10.Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.
a_10 = np.random.randint(1, 11, (3, 4))
v = np.random.randint(1, 11, (4))
res_10 = np.dot(a_10, v)
print(a_10)
print(v)
print(res_10)

[[ 2  4  7  2]
 [ 5  1  1  2]
 [ 5  6  9 10]]
[3 4 7 2]
[ 75  30 122]


In [34]:
#11.Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.
a_11 = np.random.rand(2, 3)
v_11 = np.random.rand(3)
res_11 = np.dot(a_11, v_11)
print(a_11)
print(v_11)
print(res_11)

[[0.24551127 0.79208894 0.87104654]
 [0.69793705 0.28865425 0.1360398 ]]
[0.41924065 0.36478675 0.17352692]
[0.54302188 0.42150739]


In [37]:
#12.Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.
a_12 = np.random.randint(1, 11, (2, 2))
b_12 = np.random.randint(1, 11, (2, 2))
res_12 = a_12 * b_12
print(a_12)
print(b_12)
print(res_12)

[[5 5]
 [7 2]]
[[9 5]
 [7 4]]
[[45 25]
 [49  8]]


In [40]:
#13.Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.
a_13 = np.random.randint(1, 11, (2, 2))
b_13 = np.random.randint(1, 11, (2, 2))
res_13 = np.dot(a_13, b_13)
print(a_13)
print(b_13)
print(res_13)

[[ 8  3]
 [10  8]]
[[ 7  5]
 [10  8]]
[[ 86  64]
 [150 114]]


In [41]:
#14.Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.
a_14 = np.random.randint(1, 101, (5, 5))
print(a_14)
print(a_14.sum())

[[86 31  6 90 50]
 [72 74  3 16 62]
 [51  5 63 60 16]
 [63 16  7 34 16]
 [27 86 27 58 80]]
1099


In [42]:
#15.Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
a_15 = np.random.randint(1, 11, (4, 4))
b_15 = np.random.randint(1, 11, (4, 4))
res_15 = a_15 - b_15
print(a_15)
print(b_15)
print(res_15)

[[ 4  2  6  1]
 [ 7 10  3  6]
 [ 5  1  7  9]
 [ 5  2  3  4]]
[[ 3  8 10  9]
 [ 7  9  9  8]
 [ 2  9  2  9]
 [ 5 10  6  4]]
[[ 1 -6 -4 -8]
 [ 0  1 -6 -2]
 [ 3 -8  5  0]
 [ 0 -8 -3  0]]


In [44]:
#16.Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
a_16 = np.random.rand(3, 3)
v_16 = np.sum(a_16, axis=1)
res_16 = v_16.reshape(-1, 1)
print(a_16)
print(v_16)
print(res_16)


[[0.9932605  0.96855098 0.92495944]
 [0.39517755 0.64103698 0.44075906]
 [0.66480787 0.11640911 0.69898298]]
[2.88677092 1.47697359 1.48019995]
[[2.88677092]
 [1.47697359]
 [1.48019995]]


In [49]:
#17.Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
a_17 = np.random.randint(1, 101, (3, 4))
a_sq = a_17 ** 2
print(a_17)
print(a_sq)

[[100  50  15  89]
 [ 85   5  85  11]
 [ 24  74  59  12]]
[[10000  2500   225  7921]
 [ 7225    25  7225   121]
 [  576  5476  3481   144]]


In [55]:
#18.Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.
v_18 = np.random.randint(1, 50,(4))
sqrt_v_18 = np.sqrt(v_18)
print(v_18)
print(sqrt_v_18)

[45 27 41 10]
[6.70820393 5.19615242 6.40312424 3.16227766]
